version: "3.4"

 # See: https://github.com/nginx-proxy/nginx-proxy

services:
  nginx:
    # just like the usual nginx image, but brotli enabled
    image: nginx-brotli-jwt
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "7080:80"
      - "7443:443"
    volumes:
      - ./config/nginx/conf:/etc/nginx:ro
      - ./config/nginx/self-signed-certs/nginx-selfsigned.crt:/etc/ssl/certs/default.crt:ro
      - ./config/nginx/self-signed-certs/nginx-selfsigned.key:/etc/ssl/private/default.key:ro

      - frontend-static:/static
      - svelte-static:/static-svelte
      # - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  # # nginx-dockergen:
  #   image: jwilder/docker-gen
  #   container_name: nginx-dockergen
  #   command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  #   volumes_from:
  #     - nginx
  #     - nginx-letsencrypt
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./docker/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl