version: "3.4"

 # See: https://github.com/nginx-proxy/nginx-proxy

services:
  nginx-proxy:
    # just like the usual nginx image, but brotli enabled
    image: fholzer/nginx-brotli
    container_name: nginx-proxy
    ports:
      - "7080:80"
      - "7443:443"
    volumes:
      - ./config/nginx/conf:/etc/nginx:ro
      - ./config/nginx/self-signed-certs/nginx-selfsigned.crt:/etc/ssl/certs/default.crt:ro
      - ./config/nginx/self-signed-certs/nginx-selfsigned.key:/etc/ssl/private/default.key:ro

      - frontend-static:/static
      - svelte-static:/static-svelte
      # - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  # # nginx-dockergen:
  #   image: jwilder/docker-gen
  #   container_name: nginx-dockergen
  #   command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  #   volumes_from:
  #     - nginx-proxy
  #     - nginx-proxy-letsencrypt
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./docker/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl