#!/bin/bash

# ------------------------------------------------------------------
# This script wraps docker-compose to provide environment based
# defaults and added functionality.
#
# Use it from the project root just like docker-composer
#
# example:
#
# scripts/production up
# ------------------------------------------------------------------

SCRIPTS=$(dirname "$0")
DO=$(basename "$0")
ROOT=$(realpath $SCRIPTS/..)

source $SCRIPTS/lib/config
source $SCRIPTS/lib/make-dockerignore
source $SCRIPTS/lib/custom-commands
source $SCRIPTS/lib/node-commands

# allow frontend and backend folders to be read by Dockerfile(s)
make-dockerignore frontend backend svelte

COMMON="-f docker-compose.yml"
FRONTEND="-f docker/frontend/docker-compose.yml"
BACKEND="-f docker/backend/docker-compose.yml"
POSTGRES="-f docker/postgres/docker-compose.yml"
SVELTE="-f docker/svelte/docker-compose.yml"
NGINX="-f docker/nginx/docker-compose.yml"
AUTH="-f docker/auth/docker-compose.yml"

FEATURES="-f docker/_features/static-next/docker-compose.yml -f docker/_features/static-svelte/docker-compose.yml"

handle-custom-commands "$@"
handle-node-commands "$@"
[ $STOP ] && exit 0

docker-compose $COMMON $FRONTEND $BACKEND $POSTGRES $NGINX $SVELTE $AUTH $FEATURES "$@"
